feature: добавить главный сервис (Diploma.Stage2)
ciiska5/java-explore-with-me pull request #4
Opened 2023-10-13 20:17 UTC by ciiska5

2023-10-16 20:07 UTC, alexache requested changes

2023-10-16 20:07 UTC, alexache commented on main-service-srv/src/main/java/ru/practicum/event/service/EventServiceImpl.java
> +            return allPublishedEvents.stream()
Где получение статистики?

2023-10-17 08:38 UTC, ciiska5 commented on main-service-srv/src/main/java/ru/practicum/category/service/CategoryServiceImpl.java
> +        checkCategoryUniqueness(newName);
Добавил, так как от базы возвращается 500-ое исключение, а тесты требуют 409-ое

2023-10-17 09:44 UTC, ciiska5 commented on main-service-srv/src/main/java/ru/practicum/event/model/Event.java
> +    private Long confirmedRequests;//Количество одобренных заявок на участие в данном событии
Полагаю, что если всегда его получать запросом к таблице заявок, то при необходимости получения их в цикле будет обращение к БД в цикле, что, как отмечалось ранее, неприемлемо

2023-10-17 10:56 UTC, ciiska5 commented on main-service-srv/src/main/resources/schema.sql
> +    confirmed_requests  BIGINT,
В моем случае предполагается, что указанное поле храниться в БД. Вроде как ограничений на это не было.

2023-10-17 17:53 UTC, alexache commented on main-service-srv/src/main/java/ru/practicum/event/model/Event.java
> +    private Long confirmedRequests;//Количество одобренных заявок на участие в данном событии
Поэтому можно обратиться не в цикле, а до цикла, передав список айди событий как аргумент

2023-10-17 17:54 UTC, alexache commented on main-service-srv/src/main/resources/schema.sql
> +    confirmed_requests  BIGINT,
Ограничение на это есть, это дублирование данных и риск получить некорректные данные с ручным инкрементом количества подтвержденных заявок

2023-10-17 18:01 UTC, alexache requested changes

2023-10-17 18:01 UTC, alexache commented on main-service-srv/src/main/java/ru/practicum/event/service/EventServiceImpl.java
> +                    event.setConfirmedRequests(event.getConfirmedRequests() + confirmed.size());
Проблема в этих ручных инкрементах, нет никаких гарантий, что в другом потоке или другом инстансе пода кто-то в этот же момент времени тоже не пытается подтвердить заявки и тогда можно "потерять"

2023-10-17 18:03 UTC, alexache requested changes

2023-10-17 18:03 UTC, alexache commented on main-service-srv/src/main/java/ru/practicum/event/service/EventServiceImpl.java
> +                    .map(event -> EventMapper.toEventShortDto(event, getViewStats(event)))
Помимо того, что это в цикле - еще не хватает сортировки по количеству просмотров

2023-10-19 05:37 UTC, alexache approved these changes

2023-10-19 06:34 UTC, merged