feature: добавить возможность комментирования событий (Diploma.Stage3)
ciiska5/java-explore-with-me pull request #5
Opened 2023-10-19 18:00 UTC by ciiska5

2023-10-20 06:40 UTC, alexache requested changes

2023-10-20 06:40 UTC, alexache commented on main-service-srv/src/main/java/ru/practicum/comment/controller/AdminCommentController.java
> +    @DeleteMapping
Теоретически можно еще предусмотреть редактирование комментария других пользователей (опционально)

2023-10-20 06:40 UTC, alexache commented on main-service-srv/src/main/java/ru/practicum/comment/dto/CommentDto.java
> +    @NotEmpty
Для чего валидация в "выходном" ДТО?

2023-10-20 06:40 UTC, alexache commented on main-service-srv/src/main/java/ru/practicum/comment/model/Comment.java
> +    private LocalDateTime created;//Дата и время создания комментария (в формате "yyyy-MM-dd HH:mm:ss")
Таймстемпы умеет проставлять сам JPA слой с помощью аудита - и еще хорошо бы завести второе поле, чтобы хранить дату модификации

2023-10-20 07:15 UTC, ciiska5 commented on main-service-srv/src/main/java/ru/practicum/comment/controller/AdminCommentController.java
> +    @DeleteMapping
По моему мнению будет не очень красиво, если пользователь напишет какой-либо осмысленный комментарий, а затем кто-то другой его отредактирует и, возможно, исказит первоначальный смысл автора

2023-10-21 16:52 UTC, alexache approved these changes

2023-10-21 19:50 UTC, merged